### ISSUE TITLE
How to open devTools?

### ISSUE THREAD

**Issue by yantakus** [jchapron/redux-friendlist-demo#2]
I made checkout, installed deps and started the app. It works but devTools doesn't appear. Should I open it somehow?

**Comment by neighborhood999** [comment]
@web2style if your env is Windows, you can in your terminal input：
 `set DEBUG=true && npm start`
You can try it. Hope have helpful you.

**Comment by yantakus** [comment]
Thanks, it helped. Why not mention it in the README?

**Comment by neighborhood999** [comment]
@web2style so happy I can helped you.

**Comment by jchapron** [comment]
This is now mentioned in the README, see #3
